Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,7 +9,7 @@ stages:
   - install
   - unit_test # custom stage defined in jobs::include section
   - test
-  - finalize_coverage
+  - finalize_coverage # custom stage defined in jobs::include section
   - cache
 
 env:
@@ -99,36 +99,36 @@ script:
       exit $retval
     fi
 
-# See http://stackoverflow.com/questions/21294945/error-unable-to-find-instrumentation-info-for-componentinfo
-# Instead of this (which doesn't give any output during tests execution):
-# - ./gradlew connectedCheck -PdisablePreDex --continue --stacktrace --debug
-# run:
-- |
-  ./gradlew :app:installDebug :app:installDebugAndroidTest
-  retval=$?
-  if [ $retval -ne 0 ]; then
-    echo "error on install, exit code: "$retval
-    exit $retval
-  fi
+  # See http://stackoverflow.com/questions/21294945/error-unable-to-find-instrumentation-info-for-componentinfo
+  # Instead of this (which doesn't give any output during tests execution):
+  # - ./gradlew connectedCheck -PdisablePreDex --continue --stacktrace --debug
+  # run:
+  - |
+    ./gradlew :app:installDebug :app:installDebugAndroidTest
+    retval=$?
+    if [ $retval -ne 0 ]; then
+      echo "error on install, exit code: "$retval
+      exit $retval
+    fi
 
-- |
-  adb shell am instrument -w -r -e debug false bg.devlabs.fullscreenvideoviewsample.tests/androidx.test.runner.AndroidJUnitRunner |& tee build/adb-test.log
-  retval=$?
-  if [ $retval -ne 0 ]; then
-    echo "error in adb, exit code: "$retval
-    exit $retval
-  fi
+  - |
+    adb shell am instrument -w -r -e debug false bg.devlabs.fullscreenvideoviewsample.tests/androidx.test.runner.AndroidJUnitRunner |& tee build/adb-test.log
+    retval=$?
+    if [ $retval -ne 0 ]; then
+      echo "error in adb, exit code: "$retval
+      exit $retval
+    fi
 
-# adb doesn't propagate exit code from tests, see https://code.google.com/p/android/issues/detail?id=3254
-# So we need to parse saved terminal log
-- |
-  cat build/adb-test.log | grep "INSTRUMENTATION_STATUS: stack=" | grep -v "org.junit.AssumptionViolatedException"
-  if [ $? -eq 0 ]; then
-    echo "Test failure found"
-    exit 1
-  else
-    cat build/adb-test.log | grep "OK ("
-  fi
+  # adb doesn't propagate exit code from tests, see https://code.google.com/p/android/issues/detail?id=3254
+  # So we need to parse saved terminal log
+  - |
+    cat build/adb-test.log | grep "INSTRUMENTATION_STATUS: stack=" | grep -v "org.junit.AssumptionViolatedException"
+    if [ $? -eq 0 ]; then
+      echo "Test failure found"
+      exit 1
+    else
+      cat build/adb-test.log | grep "OK ("
+    fi
 
 after_success:
   - bash <(curl -s https://codecov.io/bash)
@@ -144,4 +144,4 @@ cache:
     - $HOME/.gradle/wrapper/
 
 notifications:
-    email: false
+  email: false
